export const membersData = [
  {
    email: "lisa@test.com",
    username: "lisa",
    gender: "Female",
    dateOfBirth: "1986-07-22",
    name: "Lisa",
    created: "2020-06-24",
    lastActive: "2020-06-21",
    description:
      "Adventure seeker and coffee enthusiast. Love hiking, photography, and meeting new people. Always up for a good conversation and new experiences.",
    city: "New York",
    country: "USA",
    image: "/images/F0.jpg",
  },
  {
    email: "karen@test.com",
    username: "karen",
    gender: "Female",
    dateOfBirth: "1995-10-12",
    name: "Karen",
    created: "2019-12-09",
    lastActive: "2020-05-06",
    description:
      "Art lover and yoga instructor. Passionate about wellness and creativity. Looking for someone to share life's beautiful moments with.",
    city: "London",
    country: "UK",
    image: "/images/F1.jpg",
  },
  {
    email: "margo@test.com",
    username: "margo",
    gender: "Female",
    dateOfBirth: "1989-01-24",
    name: "Margo",
    created: "2019-08-10",
    lastActive: "2020-05-12",
    description:
      "Foodie and travel enthusiast. Love exploring new cuisines and cultures. Seeking a partner for adventures and great conversations.",
    city: "Paris",
    country: "France",
    image: "/images/F2.jpg",
  },
  {
    email: "lois@test.com",
    username: "lois",
    gender: "Female",
    dateOfBirth: "1988-06-22",
    name: "Lois",
    created: "2019-04-24",
    lastActive: "2020-06-17",
    description:
      "Music lover and beach enthusiast. Enjoy live concerts and sunset walks. Looking for someone to share life's melodies with.",
    city: "Sydney",
    country: "Australia",
    image: "/images/F3.jpg",
  },
  {
    email: "ruthie@test.com",
    username: "ruthie",
    gender: "Female",
    dateOfBirth: "1986-01-12",
    name: "Ruthie",
    created: "2019-04-30",
    lastActive: "2020-06-21",
    description:
      "Bookworm and nature lover. Enjoy quiet evenings and outdoor adventures. Seeking a partner for meaningful connections.",
    city: "Vancouver",
    country: "Canada",
    image: "/images/F4.jpg",
  },
  {
    email: "todd@test.com",
    username: "todd",
    gender: "Male",
    dateOfBirth: "1980-02-07",
    name: "Todd",
    created: "2019-04-29",
    lastActive: "2020-05-16",
    description:
      "Tech enthusiast and fitness lover. Enjoy coding and outdoor sports. Looking for someone to share adventures with.",
    city: "San Francisco",
    country: "USA",
    image: "/images/F5.jpg",
  },
  {
    email: "porter@test.com",
    username: "porter",
    gender: "Female",
    dateOfBirth: "1997-04-09",
    name: "Porter",
    created: "2020-04-05",
    lastActive: "2020-06-23",
    description:
      "Adventure seeker and coffee lover. Passionate about travel and photography. Seeking a partner for life's journey.",
    city: "Berlin",
    country: "Germany",
    image: "/images/F6.jpg",
  },
  {
    email: "mayo@test.com",
    username: "mayo",
    gender: "Male",
    dateOfBirth: "1990-03-23",
    name: "Mayo",
    created: "2020-03-14",
    lastActive: "2020-05-17",
    description:
      "Sports enthusiast and foodie. Love trying new restaurants and watching games. Looking for someone to share experiences with.",
    city: "Tokyo",
    country: "Japan",
    image: "/images/M1.jpg",
  },
  {
    email: "skinner@test.com",
    username: "skinner",
    gender: "Male",
    dateOfBirth: "1982-12-01",
    name: "Skinner",
    created: "2019-01-28",
    lastActive: "2020-06-07",
    description:
      "Music producer and beach lover. Enjoy creating beats and sunset walks. Seeking a partner for creative adventures.",
    city: "Barcelona",
    country: "Spain",
    image: "/images/M2.jpg",
  },
  {
    email: "davis@test.com",
    username: "davis",
    gender: "Male",
    dateOfBirth: "1978-03-20",
    name: "Davis",
    created: "2020-02-25",
    lastActive: "2020-06-11",
    description:
      "Artist and nature enthusiast. Love painting and hiking. Looking for someone to share creative moments with.",
    city: "Amsterdam",
    country: "Netherlands",
    image: "/images/M3.jpg",
  },
  {
    email: "davis@test.com",
    username: "davis",
    gender: "Male",
    dateOfBirth: "1978-03-20",
    name: "Davis",
    created: "2020-02-25",
    lastActive: "2020-06-11",
    description:
      "Voluptate sunt adipisicing ea nisi ex ullamco veniam dolor. Dolor do et exercitation in. Aute enim pariatur amet commodo. Deserunt consectetur quis culpa aliqua voluptate ipsum exercitation exercitation exercitation ea aliqua sunt",
    city: "Lupton",
    country: "Luxembourg",
    image: "/images/M4.jpg",
  },
];
